// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"poll.ant/internal/libs/db"
	"poll.ant/internal/server"
	"poll.ant/internal/services/users/application"
	"poll.ant/internal/services/users/infrastructure"
	"poll.ant/internal/services/users/presentation"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	healthCheckHandler := server.NewHandler()
	gormDB := db.InitDb()
	userRepository := infrastructure.NewUserRepository(gormDB)
	userService := application.NewUserService(userRepository, gormDB)
	userController := presentation.NewUserController(userService)
	serverServer := server.NewServer(healthCheckHandler, userController)
	return serverServer, nil
}
